### PR TITLE
Remove vIRQ_SetVectorX

### PR DESCRIPTION
**Pull request by AlessandroA**
@meriac
@Patater

### CODE REVIEW

**Comment by Patater** [comment]
How do we know it was unused?

The code for the removal looks good to me, but I want to make sure we are okay changing the API.

**Comment by AlessandroA** [comment]
Yes, currently the only use of the vIRQ APIs has been driven by "Just replace NVIC with vIRQ and it works", which means `vIRQ_SetVectorX` has always been out of the picture. The documentation also specified to use `vIRQ_SetVector` as it was backwards compatible (and the `X` version did not add anything new).

**Comment by Patater** [comment]
OK. Will we remove this from uvisor, too?

**Comment by AlessandroA** [comment]
Yup, see ARMmbed/uvisor@1ce90d2

**Comment by Patater** [comment]
Alright.

LGTM

**Pull request merged**
