### PR TITLE
Support Nuvoton NUC472 and M451

### PR DESCRIPTION
**Pull request by ccli8**

### CODE REVIEW

**Comment by ccli8** [comment]
Hi,
How about the merge?

**Comment by meriac** [comment]
@ccli8 Can please connect your mbed.com account with your github account, so the signed CLA is extended to your github account?

**Comment by ccli8** [comment]
@meriac Could you tell me how to connect these two accounts?

**Comment by meriac** [comment]
@ccli8 I've checked with @0xc0170 - we can merge your pull request.

**Pull request merged**
