### PR TITLE
Distinguish between release and debug binaries

### PR DESCRIPTION
**Pull request by AlessandroA**
This PR introduces the feature of picking the debug/release uVisor binaries depending on the yotta build mode.

Building with `yotta build` (defaulted to `yotta build -r`) will include the:
```bash
source/${family}/release/${configuration}.o
```
binary.

Building with `yotta build -d` will instead include the:
```bash
source/${family}/debug/${configuration}.o
```
binary.

@meriac @Patater

### CODE REVIEW

**Comment by Patater** [comment]
In "Move release binaries to new release folder", we've update the version of the binaries. Probably we shouldn't, since moving binaries shouldn't update their version.

**Comment by AlessandroA** [comment]
Yes. In fairness they were moved-and-changed in that commit. I will split it in 2 separate commits.

**Comment by AlessandroA** [comment]
Split last one into 2 commits.

**Comment by Patater** [comment]
But then they were changed again, I guess. And they were already in two commits, I thought.

Anyway, now it LGTM.

**Pull request merged**
